import random as rd
import pygame
FLAG_WIDTH =
FLAG_HEIGHT =
WINDOW_HEIGHT =
WINDOW_WIDTH =
PLAYER_LOCATION =
FLAG_LOCATION =
GREEN = (138, 201, 38)
BLACK = (0, 0, 0)
BORDER_COLOR = GREEN
LOSE_MESSAGE = "You Lost!"
WIN_MESSAGE = "You Won!"
LOSE_COLOR = BLACK
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
WIN_FONT_SIZE = LOSE_FONT_SIZE
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
