import random as rd
import pygame
BLOCK_SIZE = 25
LINE_COLOR = (0,150,0)
NUM_ROW = 25
NUM_COL = 50
WINDOW_HEIGHT = NUM_ROW * BLOCK_SIZE
WINDOW_WIDTH = NUM_COL * BLOCK_SIZE

WINDOW_HEIGHT = 720#אורך הלוח
WINDOW_WIDTH = 1280#רוחב לוח

# MOVE_LENGTH = ''
FLAG_WIDTH = 40
FLAG_HEIGHT = 30
PLAYER_WIDTH = 100
PLAYER_HEIGHT = 100
PLAYER_LOCATION = [0,0]
# FLAG_LOCATION = ''
GREEN = (0, 100, 0)
BLACK = (0, 0, 0)
BORDER_COLOR = GREEN
LOSE_MESSAGE = "You Lost!"
WIN_MESSAGE = "You Won!"
LOSE_COLOR = BLACK
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
WIN_FONT_SIZE = LOSE_FONT_SIZE
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
TOTAL_NUM_BOMB = 20
TOTAL_NUM_GRASS = 20
RowAmount = 25
CallumnAmount = 50
MinesAmmount = 20 #Bomb